### ISSUE TITLE
Problem with RSAEncryptionPadding

### ISSUE THREAD

**Issue by cccrc** [mlaily/KeePass-CertificateShortcutProvider#4]
Hey mlaily, thanks for implementing this way of using the smart card. I like it better than the signing variant that I found. I have an issue using it though:

My system throws an Error complaining about the padding mode for a certain algorithm. I guess the problem is, that my certificates aren't OaepSHA256 compatible and I can't change them for the time being.  Do you see an practical way around this or would it possible for you to provide an Pkcs1 build?

**Comment by mlaily** [comment]
Hello,
I guess providing a choice for the RSA padding algorithm is possible, but I wouldn't want to hard-code it so it would require a bit of work to add it to the .cspkey file...  
Before going this route I would like to make sure there is no way around it.

Could you share all the information you have about the error you are getting? (Exact error message and such)

[The comment on this stackoverflow thread](https://stackoverflow.com/questions/56489969/why-does-rsa-encryption-error-with-rsaencryptionpadding-oaepsha256#comment99599091_56489969) seems to indicate it might be due to an old version of .NET Framework.

Could you check which version of .NET you have, and try installing the latest version if it's not already the case? (https://dotnet.microsoft.com/en-us/download/dotnet-framework/net48)

**Comment by cccrc** [comment]
Hi,
I checked and can confirm that I'm using .NET 4.8.

For the error details:
Message: **"The specified padding mode is not valid for this algorithm."**
see:
https://docs.microsoft.com/en-us/dotnet/api/system.security.cryptography.x509certificates.x509signaturegenerator.createforrsa?view=net-6.0

The only meaningful thing i could find in Windows-Event-Log is the following error:
Message: (translated) **The operation to open the provider failed.** 
```
- System
  - Provider 
   [ Name]  **Microsoft-Windows-Crypto-NCrypt** 
   [ Guid]  {e8ed09dc-100c-45e2-9fc8-b53399ec1f70} 
   EventID 2 
   Version 0 
   Level 2 
   Task 2 
   Opcode 0 
   Keywords 0x8000000000000001 
 
  - TimeCreated
   [ SystemTime]  2022-05-25T16:42:31.3254787Z 
   EventRecordID 596 
   Correlation 
 
  - Execution 
   [ ProcessID]  1234 
   [ ThreadID]  1234 
   Channel Microsoft-Windows-Crypto-NCrypt/Operational 
   Computer xyz.abc.sec 
 
  - Security 
   [ UserID]  S-42 
 
- EventData 
  **ProviderName Personal CSP 
  Status 0xc0000225 
  ProcessName KeePass.exe** 
  
```
  
  I tried the following plugin. It's using the Pkcs1 padding and that works for me:
  https://github.com/BodnarSoft/KeePass-Smart-Certificate-Key-Provider
`  rsa.SignData("some text ...", HashAlgorithmName.SHA1, RSASignaturePadding.Pkcs1);`

**Comment by mlaily** [comment]
Ok, I'm still not 100% convinced this cannot be solved by somehow setting a correct provider for the certificate in the store, but I don't have definitive proof and I have no idea how one would do that.

So I implemented it. Can you try https://github.com/mlaily/KeePass-CertificateShortcutProvider/releases/download/1.4.0/CertificateShortcutProvider.dll? (look for the "Advanced settings" button in the key creation window)

**Comment by cccrc** [comment]
That is great. It works perfectly now. Thanks for your support.

**Comment by mlaily** [comment]
Glad to hear that!
